name: Sync linux-firmware repository

on:
  schedule:
    # Trigger every Sunday at 5:00
    - cron: '0 5 * * 0'

jobs:
  sync-linux-firmware:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip3 install 'cryptography>=2.5'
        pip3 install 'construct>=2.10'

    - name: Sync linux-firmware repository
      run: ./sync_linux_firmware.py && ./sync_linux_firmware.py > output_linux_firmware.txt

    - name: Update SHA256SUM.txt
      run: ./update_sha256sum.sh

    - name: Show git status
      run: git status

    - name: Show git diff
      run: git diff

    - name: Commit the diff
      run: |
        if git status --short | grep '^' ; then
            git config user.name "Automatic Updater"
            git config user.email "automatic-updater"
            git add --all .
            git commit -m "Sync linux-firmware repository $(date --utc +"%Y-%m-%d %H:%M:%S")"
            git push origin main
        fi

    - name: Regenerate descriptions
      run: rm -rf descriptions && ./update_descriptions.py

    - name: Show git status
      run: git status

    - name: Show git diff
      run: git diff

    - name: Commit the diff
      run: |
        if git status --short | grep '^' ; then
            git config user.name "Automatic Updater"
            git config user.email "automatic-updater"
            git add --all .
            git commit -m "Update firmware descriptions $(date --utc +"%Y-%m-%d %H:%M:%S")"
            git push origin main
        fi

